# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: af55c383227e74c5b69664856240730cd5c396b7a066086ea54ea5911dcd1e52832a54e29a560f7b3b13c51f77781eaa5f2005541a8f78d86be94a684f789f62

test:
  secret_key_base: 1afd053e4f0fe9ca9b4007d303623e69070ccc66f4e4208966de8aef61735f4f70fcde91f6b8d653d29c3c0e6df5f36310f90b2bf25ac4ace34ff784a73d6093

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
